FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./web_app/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./web_app/app.py /app

EXPOSE 5000

CMD ["python", "app.py"]
